name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "dev"

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: env/${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: hashicorp/setup-terraform@v2
      
      - run: terraform init -reconfigure
      - run: terraform force-unlock -force fbc60317-0901-beaf-29aa-c8fe8d98e007
      - run: terraform plan
      - run: terraform validate
      - run: terraform apply -auto-approve
      #- run: terraform destroy -auto-approve
